### ISSUE TITLE
Control close times

### ISSUE THREAD

**Issue by thomie** [marktron/pbpcalc#3]
Hello @marktron,

Thank you for this project.

What is your source for the control end times? 

For example, `data/control.js` contains:
```
  {
    distance: 203,
    elapsedTime: null,
    location: "Villaines-la-Juhel",
    type: "CONTROL",
    closingTime: {
      hours80: 765,
      hours84: 787,
      hours90: 868,
    },
  },
```

So for the 90 hour starting groups, the control at kilometer 203 supposedly closes `868` minutes after the start.

But I found https://rusa.org/octime_rm.html, which claims the 90 hour PBP need to complete the first 203 (up to 600) kilometers with a minimal speed of 15 km/h. This translates to a close at `812` minutes  (`203/15*60=812`).

So that's quite a big difference (56 minutes!), and I wonder which one is correct.

Is there an official source from ACP that you know of?

**Comment by thomie** [comment]
> Is there an official source from ACP that you know of?

Here is the Control Timetable for the 84 hour time limit group, from the documents that ACP provides with my PBP registration.

Interestingly the control close times are different from both the ones given by this github project and the rusa website I mentioned earlier.

----------

Start on Monday, Aug. 21, 2023 (84 h time limit)

(calculated on the basis of a start at 05h00, to be adjusted to your real start time)

You will have the schedules of your departure wave on your brevet card

CONTROLS | Km | Opening | Closing
-- | -- | -- | --
RAMBOUILLET | 0 | 21/8 | 05:00 |   |  
Mortagne-au-Perche (services only) | 119 | 21/8 | 08:26 | 21/8 | 12:14
VILLAINES-LA-JUHEL | 203 | 21/8 | 11:01 | 21/8 | 17:24
FOUGERES | 292 | 21/8 | 14:01 | 21/8 | 22:59
TINTENIAC | 353 | 21/8 | 16:03 | 22/8 | 02:48
Quédillac (services only) | 378 | 21/8 | 16:55 | 22/8 | 04:26
LOUDEAC | 435 | 21/8 | 18:50 | 22/8 | 08:01
Saint-Nicolas-du-Pélem (services only) | 482 | 21/8 | 20:28 | 22/8 | 11:06
CARHAIX-PLOUGUER | 514 | 21/8 | 21:33 | 22/8 | 13:14
BREST | 604 | 22/8 | 00:46 | 22/8 | 19:15
CARHAIX-PLOUGUER | 697 | 22/8 | 04:21 | 23/8 | 01:54
Gouarec (services only) | 731 | 22/8 | 05:36 | 23/8 | 04:14
LOUDEAC | 782 | 22/8 | 07:42 | 23/8 | 07:59
Quédillac (services only) | 842 | 22/8 | 10:25 | 23/8 | 12:19
TINTENIAC | 867 | 22/8 | 11:33 | 23/8 | 14:06
FOUGERES | 928 | 22/8 | 14:19 | 23/8 | 18:26
VILLAINES-LA-JUHEL | 1017 | 22/8 | 18:23 | 24/8 | 00:50
MORTAGNE-AU-PERCHE | 1099 | 22/8 | 22:05 | 24/8 | 07:06
DREUX | 1176 | 23/8 | 01:45 | 24/8 | 13:31
RAMBOUILLET | 1219 | 23/8 | 03:50 | 24/8 | 17:00

**Comment by marktron** [comment]
Hi @thomie – I originally pulled the data from 2019 control times, but Audax Club Parisien has now published the official closing times for 2023 for all three start times, which I've incorporated into the calculator.

- [80 hours](https://myaccount.audax-club-parisien.com/vue/pbp/dossier/GB/2023-GB-J1.docx)
- [84 hours](https://myaccount.audax-club-parisien.com/vue/pbp/dossier/GB/2023-GB-J3.docx)
- [90 hours](https://myaccount.audax-club-parisien.com/vue/pbp/dossier/GB/2023-GB-J2.docx)

**Comment by thomie** [comment]
Excellent. Thank you @marktron.
